spring.profiles.active: develop
server:
  port: 8090
---
spring:
  profiles: develop
  jpa:
    show_sql: true
    database: H2
    database-platform: "org.hibernate.dialect.H2Dialect"
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  logging:
    level:
      root: DEBUG

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialization-mode: NEVER

stripe.simulator.charges-uri: https://sandbox.playtomic.io/v1/stripe-simulator/charges
stripe.simulator.refunds-uri: https://sandbox.playtomic.io/v1/stripe-simulator/payments/{payment_id}/refunds
---
spring:
  profiles: test
  jpa:
    show_sql: true
    database: H2

  logging:
    level:
      root: DEBUG
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialization-mode: NEVER

stripe.simulator.charges-uri: http://localhost:9999
stripe.simulator.refunds-uri: http://localhost:9999